# Generated by Django 2.1.4 on 2018-12-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despesa',
        ),
    ]
